apiVersion: apps/v1
kind: Deployment
metadata:
  name: vivekanand-portfoilo
  labels:
    app: vivekanand-portfoilo-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vivekanand-portfoilo
  template:
    metadata:
      labels:
        app: vivekanand-portfoilo
    spec:
      containers:
      - name: vivekanand-portfoilo-container
        image: vivekguatam07/mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vivekanand-portfoilo
  labels:
    app: vivekanand-portfoilo
spec:
  selector:
    app:vivekanand-portfoilo-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
